name: edukasi_mobile
description: Edukasi Mobile for Parents.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: "^1.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^2.0.0
  equatable: ^0.6.1
  shared_preferences: ^0.5.4+3

  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true 
  ios: false
  image_path: "assets/images/edukasi-mark.png"

flutter:
  uses-material-design: true

  fonts:
  - family: CustomIcons
    fonts:
    - asset: assets/fonts/CustomIcons.ttf
  - family: Okomito
    fonts:
    - asset: assets/fonts/Okomito-Regular.ttf
      weight: 400
  - family: Circular
    fonts:
    - asset: assets/fonts/CircularStd-Bold.otf
      weight: 700
  - family: Circular Book
    fonts:
    - asset: assets/fonts/CircularStd-Book.otf
      weight: 300

  assets:
   - assets/images/