name: edukasi_mobile
description: Edukasi Mobile for Parents.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: "^1.7.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
  - family: CustomIcons
    fonts:
    - asset: assets/fonts/CustomIcons.ttf
  - family: Okomito
    fonts:
    - asset: assets/fonts/Okomito-Regular.ttf
      weight: 400
  - family: Circular
    fonts:
    - asset: assets/fonts/CircularStd-Bold.otf
      weight: 700
  - family: Circular Book
    fonts:
    - asset: assets/fonts/CircularStd-Book.otf
      weight: 300